/*
 * This file is generated by jOOQ.
 */
package com.tosin.notez.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Files implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String title;
    private String filename;
    private UUID userId;
    private String type;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Files() {}

    public Files(Files value) {
        this.id = value.id;
        this.title = value.title;
        this.filename = value.filename;
        this.userId = value.userId;
        this.type = value.type;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    @ConstructorProperties({ "id", "title", "filename", "userId", "type", "createdAt", "updatedAt" })
    public Files(
        UUID id,
        String title,
        String filename,
        UUID userId,
        String type,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.title = title;
        this.filename = filename;
        this.userId = userId;
        this.type = type;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>files.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>files.id</code>.
     */
    public Files setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>files.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>files.title</code>.
     */
    public Files setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>files.filename</code>.
     */
    public String getFilename() {
        return this.filename;
    }

    /**
     * Setter for <code>files.filename</code>.
     */
    public Files setFilename(String filename) {
        this.filename = filename;
        return this;
    }

    /**
     * Getter for <code>files.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>files.user_id</code>.
     */
    public Files setUserId(UUID userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>files.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>files.type</code>.
     */
    public Files setType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Getter for <code>files.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>files.created_at</code>.
     */
    public Files setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>files.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>files.updated_at</code>.
     */
    public Files setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Files other = (Files) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.filename == null) {
            if (other.filename != null)
                return false;
        }
        else if (!this.filename.equals(other.filename))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.filename == null) ? 0 : this.filename.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Files (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(filename);
        sb.append(", ").append(userId);
        sb.append(", ").append(type);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
