/*
 * This file is generated by jOOQ.
 */
package com.tosin.notez.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notes implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String title;
    private String textContent;
    private UUID categoryId;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private UUID userId;

    public Notes() {}

    public Notes(Notes value) {
        this.id = value.id;
        this.title = value.title;
        this.textContent = value.textContent;
        this.categoryId = value.categoryId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.userId = value.userId;
    }

    @ConstructorProperties({ "id", "title", "textContent", "categoryId", "createdAt", "updatedAt", "userId" })
    public Notes(
        UUID id,
        String title,
        String textContent,
        UUID categoryId,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        UUID userId
    ) {
        this.id = id;
        this.title = title;
        this.textContent = textContent;
        this.categoryId = categoryId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.userId = userId;
    }

    /**
     * Getter for <code>notes.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>notes.id</code>.
     */
    public Notes setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>notes.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>notes.title</code>.
     */
    public Notes setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>notes.text_content</code>.
     */
    public String getTextContent() {
        return this.textContent;
    }

    /**
     * Setter for <code>notes.text_content</code>.
     */
    public Notes setTextContent(String textContent) {
        this.textContent = textContent;
        return this;
    }

    /**
     * Getter for <code>notes.category_id</code>.
     */
    public UUID getCategoryId() {
        return this.categoryId;
    }

    /**
     * Setter for <code>notes.category_id</code>.
     */
    public Notes setCategoryId(UUID categoryId) {
        this.categoryId = categoryId;
        return this;
    }

    /**
     * Getter for <code>notes.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>notes.created_at</code>.
     */
    public Notes setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>notes.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>notes.updated_at</code>.
     */
    public Notes setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for <code>notes.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>notes.user_id</code>.
     */
    public Notes setUserId(UUID userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Notes other = (Notes) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.textContent == null) {
            if (other.textContent != null)
                return false;
        }
        else if (!this.textContent.equals(other.textContent))
            return false;
        if (this.categoryId == null) {
            if (other.categoryId != null)
                return false;
        }
        else if (!this.categoryId.equals(other.categoryId))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.textContent == null) ? 0 : this.textContent.hashCode());
        result = prime * result + ((this.categoryId == null) ? 0 : this.categoryId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Notes (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(textContent);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
