name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # For semantic versioning tags like v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Step 4: Extract version from gradle.properties and set as environment variable
      - name: Extract version
        run: |
          echo VERSION=$(grep "version" ./gradle.properties | awk '{split($0,a,"="); print a[2]}') >> $GITHUB_ENV

      # Step 5: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/notez_backend:${{ env.VERSION }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/notez_backend:${{ env.VERSION }} ${{ secrets.DOCKER_HUB_USERNAME }}/notez_backend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/notez_backend:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/notez_backend:latest
